---
openapi: 3.0.1
info:
  title: API V1
  version: v1
host: ''
basePath: "/api/v1"
paths:
  "/contacts":
    get:
      summary: List all contacts
      tags:
      - Contact
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        schema:
          type: integer
      - name: filter[search_by_tag]
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  contacts:
                    type: array
                    description: An arrray of contacts
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: '1'
                        full_name:
                          type: string
                          example: John Doe
                        email:
                          type: string
                          example: exmaple@example.com
                        tags:
                          type: array
                          description: Contact tags
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                                example: '1'
                              name:
                                type: string
                                example: lead
                              camel_case_name:
                                type: string
                                example: HighValued
    post:
      summary: Create contact
      tags:
      - Contact
      parameters: []
      responses:
        '200':
          description: success
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                contact:
                  type: object
                  properties:
                    email:
                      type: string
                      example: test@example.com
                    first_name:
                      type: string
                      example: john
                    last_name:
                      type: string
                      example: doe
                    tags_attributes:
                      type: array
                      description: array of tags for contact (new or existing)
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            example: win
  "/contacts/{id}":
    put:
      summary: Update contact
      tags:
      - Contact
      parameters:
      - name: id
        in: path
        description: contact id
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: success
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                contact:
                  type: object
                  properties:
                    email:
                      type: string
                      example: test@example.com
                    first_name:
                      type: string
                      example: john
                    last_name:
                      type: string
                      example: doe
                    tags_attributes:
                      type: array
                      description: array of tags for contact (new or existing)
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            example: win
    delete:
      summary: Delete contact
      tags:
      - Contact
      parameters:
      - name: id
        in: path
        description: contact id
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: success
servers:
- url: http://localhost:3000/api/v1
