---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/contacts":
    get:
      summary: List all contacts
      tags:
      - Contact
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        schema:
          type: integer
      - name: filter[search_by_tag]
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: success
    post:
      summary: Create contact
      tags:
      - Contact
      parameters: []
      responses:
        '200':
          description: success
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                contact:
                  type: object
                  properties:
                    email:
                      type: string
                      example: test@example.com
                    first_name:
                      type: string
                      example: john
                    last_name:
                      type: string
                      example: doe
                    tags_attributes:
                      type: array
                      description: array of tags for contact (new or existing)
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            example: win
  "/contacts/{id}":
    put:
      summary: Update contact
      tags:
      - Contact
      parameters:
      - name: id
        in: path
        description: contact id
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: success
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                contact:
                  type: object
                  properties:
                    email:
                      type: string
                      example: test@example.com
                    first_name:
                      type: string
                      example: john
                    last_name:
                      type: string
                      example: doe
                    tags_attributes:
                      type: array
                      description: array of tags for contact (new or existing)
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            example: win
    delete:
      summary: delete contact
      tags:
      - Contact
      parameters:
      - name: id
        in: path
        description: contact id
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: success
servers:
- url: http://localhost:3000/api/v1
